name: test

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: sleep 5

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
